.PHONY: help
help:
	@echo "Available 'make' targets"
	@echo "  all    Converts .adoc to .html using the 'asciidoctor' tool"

.PHONY: all
all:
	asciidoctor  How_to_Contribute.adoc

clean full_clean:
	rm -r -f *~
