# Include the boilerplate for bsc-contrib tests
set here [file join [absolute $srcdir] $subdir]
source $here/../../contrib.tcl

if { $contribtest } {

    add_contrib_dirs_to_path { AMBA_Fabrics/AXI4_Lite  Misc }

    # Because we use 'genC' to correct the 'cur_cycle', the .ba file
    # is specific to the backend and cannot be reused for the other,
    # so we use the '_separately' variant of the test procedure
    #
    test_c_veri_bsv_separately  Test_Fabric

    restore_path

}
