# Include the boilerplate for bsc-contrib tests
set here [file join [absolute $srcdir] $subdir]
source $here/../contrib.tcl

if { $contribtest } {

    add_contrib_dirs_to_path { GenCRepr GenCMsg }

    compile_pass Counter.bs
    copy counter_driver.c.keep counter_driver.c
    test_c_only_multi Counter sysCounter { messageAvailable.ba getMessage.ba putMessage.ba counter_driver.c counter.c } "" "" 1

    test_c_veri CounterB2B "" "" "" 1

    restore_path

}
